apiVersion: v1
kind: Service
metadata:
  name: fitreview-api
  labels:
    app: fitreview-api
spec:
  selector:
    app: fitreview-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
